### ISSUE TITLE
提现接口

### ISSUE THREAD

**Issue by cwx2810** [gateio/gateapi-java#11]
调提现接口会发短信提示被安全审核，app里提现就不会这样
传了address、currency、amount、chain，4个参数，是少传了什么参数还是因为是新地址，或者换ip的问题触发了安全审核？怎样可以避免呢？

**Comment by revilwang** [comment]
API 的提现安全等级比较高，具体触发原因可以直接咨询在线客服，这里一般只解决技术问题
