### ISSUE TITLE
How to convert fee to USDT?

### ISSUE THREAD

**Issue by Freeongoo** [gateio/gateapi-java#17]
Get transaction history (Trade) for pair **APRT_USDT**.

when a sell operation, everything is clear here, since the fee is displayed in USDT:

```
class Trade {
      id: 4757428860
      createTime: 1671090792
      createTimeMs: 1671090792679.394000
      currencyPair: APRT_USDT
      side: sell
      role: maker
      amount: 719.2
      price: 0.0014169
      orderId: 244554016122
      fee: 0.00203806896
      feeCurrency: USDT
      pointFee: 0
      gtFee: 0
}
```

But I do not understand how to convert the fee to USDT when buying, it is indicated here that the fee is in APRT

```
class Trade {
      id: 4756751445
      createTime: 1671087875
      createTimeMs: 1671087875246.492000
      currencyPair: APRT_USDT
      side: buy
      role: taker
      amount: 720.66
      price: 0.0013876
      orderId: 244553641725
      fee: 1.44132
      feeCurrency: APRT
      pointFee: 0
      gtFee: 0
}
```

please show me how to convert here 1.44132 APRT => ? USDT

**Comment by revilwang** [comment]
When buying, you get APRT, so the deducted fee is from the ARPT you get.
If you want to know how much the fee is in USDT, you can use Trade.price * Trade.fee

**Comment by Freeongoo** [comment]
@revilwang  Thanks a lot
