### ISSUE TITLE
Failed to resolve: io.gate:gate-api:4.11.0

### ISSUE THREAD

**Issue by a454892215** [gateio/gateapi-java#2]
我在gradle 加了配置： implementation  "io.gate:gate-api:4.11.0" 但是一直提示    implementation  "io.gate:gate-api:4.11.0"

我的仓库地址配置
allprojects {
    repositories {
      //  maven{url 'http://maven.aliyun.com/nexus/content/groups/public/'}
        maven{url 'file:D:\\work\\projects\\Common\\androidAppUtil\\repository'}
        maven{url 'D:\\work\\projects\\Common\\Common\\repository'}
        google()
        jcenter()
        mavenCentral()
        maven{url 'https://jitpack.io'}
        maven {
            url "https://maven.google.com" // Google's Maven repository
        }
    }
}

**Comment by revilwang** [comment]
没发布到maven仓库去，目前只能手工添加jar包来操作
