### ISSUE TITLE
现货限频规则

### ISSUE THREAD

**Issue by leoyey** [gateio/gateapi-java#4]
Gate的API文档(https://www.gate.io/docs/apiv4/zh_CN/index.html#c1fd2fc5ac)写着得限频规则是：

提现：
提现接口限制每个用户 10s 一次请求

现货：
查询请求按源 IP 限制每秒 300 次请求

合约：
私有接口的请求频率按用户限制在每秒总计 400 个请求
永续合约、交割合约共享同一个频率限制

这里写着现货的查询请求是按照IP限频的，并没有说明现货的是有接口，比如下单、撤单的限频规则。
请问现货的私有接口限频规则是什么样的？是跟合约一样，按照用户限频的吗？

**Comment by revilwang** [comment]
限频当前还在适度调整中，现货私有接口目前是按照 API Key 限制，下单撤单与其他私有接口共享限频，300r/s

**Comment by leoyey** [comment]
了解。如果规则有更新，请在API文档中也相应的更新一下。
